export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  Profile: undefined;
  InterestConfirmation: { userId: string; loanType?: 'nano' | 'term' };
  TermLoans: undefined;
  BankingDetails: undefined;
  NetDisposableIncome: undefined;
  BankAuthorization: undefined;
  TermInterestConfirmation: undefined;
  CreditScoreHistory: undefined;
  Statement: undefined;
  PaymentRecord: undefined;
  LoanHistory: undefined;
  NanoLoanApply: undefined;
  TermLoanApply: undefined;
  ForgotPassword: undefined;
  ForgotPasswordOtp: { mobileNumber: string };
  ForgotPasswordNewPin: { mobileNumber: string };
  RegisterReferral: undefined;
  RegisterLinkCommunity: { referralPartner: string; lendingSociety: string; portfolioHolder: string };
  RegisterPersonalInfo: undefined;
  RegisterEmployerKin: undefined;
  RegisterSetPin: { mobileNumber: string };
  RegisterOtp: { mobileNumber: string };
  RegisterKyc: undefined;
  RegisterDocuments: undefined;
  RegisterSuccess: undefined;
};
